FROM alpine:3.23

ARG OXIDIZED_VERSION=0.37.0
ENV OXIDIZED_HOME=/etc/oxidized

RUN set -eux; \
  \
  # Install runtime deps
  apk add --no-cache \
    ruby \
    ruby-rugged \
    libssh2 \
    icu-libs \
    zlib \
    openssl \
    msmtp \
    bash \
    git \
  ; \
  \
  # Install build deps (temporary)
  apk add --no-cache --virtual .build-deps \
    ruby-dev \
    g++ \
    cmake \
    make \
    openssl-dev \
    icu-dev \
    zlib-dev \
    linux-headers \
  ; \
  \
  # Install gems
  gem install --no-document \
    "oxidized:${OXIDIZED_VERSION}" \
    oxidized-web \
  ; \
  \
  # Resolve gem directory dynamically
  GEM_DIR="$(ruby -e 'print Gem.default_dir')"; \
  \
  # Install helper script into stable PATH location
  install -m 0755 \
    "${GEM_DIR}/gems/oxidized-${OXIDIZED_VERSION}/extra/oxidized-report-git-commits" \
    /usr/local/bin/oxidized-report-git-commits \
  ; \
  \
  # Cleanup
  find "${GEM_DIR}/cache" -mindepth 1 -delete; \
  apk del .build-deps; \
  rm -rf /var/cache/apk/*

RUN addgroup -S oxidized \
 && adduser -S -G oxidized oxidized \
 && mkdir -p "${OXIDIZED_HOME}" \
 && chown -R oxidized:oxidized "${OXIDIZED_HOME}"

USER oxidized
WORKDIR ${OXIDIZED_HOME}

EXPOSE 8888
CMD ["oxidized"]

LABEL org.opencontainers.image.authors="Will Brickles" \
      org.opencontainers.image.title="oxidized" \
      org.opencontainers.image.description="software to backup network switch configurations" \
      org.opencontainers.image.version="${OXIDIZED_VERSION}"
